export const UsersList = [
  {
    id: 1,
    username: 'jdoe',
    firstName: 'John',
    lastName: 'Doe',
    telegram: '@johndoe',
    registrationDate: '2024-11-01',
    avatar: '/static_uploads/avatars/user1.jpeg',
  },
  {
    id: 2,
    username: 'asmith',
    firstName: 'Alice',
    lastName: 'Smith',
    telegram: '@alicesmith',
    registrationDate: '2024-11-02',
    avatar: '/static_uploads/avatars/user2.jpeg',
  },
  {
    id: 3,
    username: 'bwayne',
    firstName: 'Bruce',
    lastName: 'Wayne',
    telegram: '@batman',
    registrationDate: '2024-11-03',
    avatar: '/static_uploads/avatars/user3.jpeg',
  },
  {
    id: 4,
    username: 'ckent',
    firstName: 'Clark',
    lastName: 'Kent',
    telegram: '@superman',
    registrationDate: '2024-11-04',
    avatar: '/static_uploads/avatars/user4.jpeg',
  },
  {
    id: 5,
    username: 'dprince',
    firstName: 'Diana',
    lastName: 'Prince',
    telegram: '@wonderwoman',
    registrationDate: '2024-11-05',
    avatar: '/static_uploads/avatars/user5.jpeg',
  },
  {
    id: 6,
    username: 'tstark',
    firstName: 'Tony',
    lastName: 'Stark',
    telegram: '@ironman',
    registrationDate: '2024-11-06',
    avatar: '/static_uploads/avatars/user6.jpeg',
  },
  {
    id: 7,
    username: 'pparker',
    firstName: 'Peter',
    lastName: 'Parker',
    telegram: '@spiderman',
    registrationDate: '2024-11-07',
    avatar: '/static_uploads/avatars/user7.jpeg',
  },
  {
    id: 8,
    username: 'srogers',
    firstName: 'Steve',
    lastName: 'Rogers',
    telegram: '@captainamerica',
    registrationDate: '2024-11-08',
    avatar: '/static_uploads/avatars/user8.jpeg',
  },
  {
    id: 9,
    username: 'banner',
    firstName: 'Bruce',
    lastName: 'Banner',
    telegram: '@hulk',
    registrationDate: '2024-11-09',
    avatar: '/static_uploads/avatars/user9.jpeg',
  },
  {
    id: 10,
    username: 'nromanoff',
    firstName: 'Natasha',
    lastName: 'Romanoff',
    telegram: '@blackwidow',
    registrationDate: '2024-11-10',
    avatar: '/static_uploads/avatars/user10.jpeg',
  },
];
